"""Vehicle ステータス

Revision ID: 02cc65b567d1
Revises: 4d50879d53fa
Create Date: 2025-05-17 17:04:20.504264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02cc65b567d1'
down_revision = '4d50879d53fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('courses', schema=None) as batch_op:
     #   batch_op.alter_column('fld_コースID',
      #         existing_type=sa.SMALLINT(),
       #        server_default=None,
        #       existing_nullable=False,
         #      autoincrement=True)

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ステータス', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('車名', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('車名')
        batch_op.drop_column('ステータス')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('fld_コースID',
               existing_type=sa.SMALLINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
