"""Maintenance table create

Revision ID: 05d00ba050bb
Revises: 02cc65b567d1
Create Date: 2025-05-19 13:37:37.579442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d00ba050bb'
down_revision = '02cc65b567d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='状態名'),
    sa.Column('description', sa.Text(), nullable=True, comment='説明'),
    sa.Column('color_code', sa.String(length=7), nullable=True, comment='色コード（例：#FF0000）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='点検種類名'),
    sa.Column('description', sa.Text(), nullable=True, comment='説明'),
    sa.Column('cycle_months', sa.Integer(), nullable=True, comment='点検周期（月）'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='有効フラグ'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False, comment='車両ID'),
    sa.Column('maintenance_type_id', sa.Integer(), nullable=False, comment='点検種類ID'),
    sa.Column('scheduled_date', sa.Date(), nullable=False, comment='予定日'),
    sa.Column('completion_date', sa.Date(), nullable=True, comment='完了日'),
    sa.Column('status_id', sa.Integer(), nullable=False, comment='状態ID'),
    sa.Column('technician', sa.String(length=100), nullable=True, comment='担当者'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='実施場所'),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True, comment='費用'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備考'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['maintenance_type_id'], ['maintenance_types.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['maintenance_statuses.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_schedule_id', sa.Integer(), nullable=False, comment='整備予定ID'),
    sa.Column('item_name', sa.String(length=100), nullable=False, comment='点検項目名'),
    sa.Column('result', sa.String(length=100), nullable=True, comment='点検結果'),
    sa.Column('is_ok', sa.Boolean(), nullable=True, comment='合否フラグ'),
    sa.Column('action_taken', sa.Text(), nullable=True, comment='実施内容'),
    sa.Column('parts_used', sa.Text(), nullable=True, comment='使用部品'),
    sa.Column('parts_cost', sa.Numeric(precision=10, scale=2), nullable=True, comment='部品費用'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備考'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['maintenance_schedule_id'], ['maintenance_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_schedule_id', sa.Integer(), nullable=False, comment='整備予定ID'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='ファイル名'),
    sa.Column('file_path', sa.String(length=255), nullable=False, comment='ファイルパス'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='ファイルタイプ'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='ファイルサイズ（バイト）'),
    sa.Column('description', sa.Text(), nullable=True, comment='説明'),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True, comment='アップロード者'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='作成日時'),
    sa.ForeignKeyConstraint(['maintenance_schedule_id'], ['maintenance_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #with op.batch_alter_table('courses', schema=None) as batch_op:
    #    batch_op.alter_column('fld_コースID',
    #           existing_type=sa.SMALLINT(),
    #           server_default=None,
    #           existing_nullable=False,
    #           autoincrement=True)

    #with op.batch_alter_table('vehicles', schema=None) as batch_op:
    #    batch_op.alter_column('初年度登録年月',
    #           existing_type=sa.TEXT(),
    #           type_=sa.String(),
    #           existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('初年度登録年月',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('fld_コースID',
               existing_type=sa.SMALLINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    op.drop_table('maintenance_files')
    op.drop_table('maintenance_details')
    op.drop_table('maintenance_schedules')
    op.drop_table('maintenance_types')
    op.drop_table('maintenance_statuses')
    # ### end Alembic commands ###
