"""Add eneoswing

Revision ID: 11b672caa2a3
Revises: 0789b487435d
Create Date: 2025-06-10 12:18:37.371341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b672caa2a3'
down_revision = '0789b487435d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eneos_wing_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=True, comment='実車番・届先'),
    sa.Column('station_code', sa.String(length=20), nullable=True, comment='給油ＳＳコード'),
    sa.Column('station_name', sa.String(length=100), nullable=True, comment='給油ＳＳ名称'),
    sa.Column('fuel_date', sa.Date(), nullable=False, comment='給油日付'),
    sa.Column('fuel_time', sa.Time(), nullable=True, comment='給油時刻'),
    sa.Column('receipt_number', sa.String(length=20), nullable=True, comment='レシート番号'),
    sa.Column('product_category', sa.String(length=10), nullable=True, comment='商品分類'),
    sa.Column('product_code', sa.String(length=10), nullable=True, comment='商品コード'),
    sa.Column('package_code', sa.String(length=10), nullable=True, comment='荷姿コード'),
    sa.Column('product_name', sa.String(length=100), nullable=True, comment='商品名称'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True, comment='数量'),
    sa.Column('converted_quantity', sa.Numeric(precision=10, scale=3), nullable=True, comment='換算後数量'),
    sa.Column('unit_price_with_tax', sa.Numeric(precision=10, scale=2), nullable=True, comment='単価（軽油税込）'),
    sa.Column('unit_price_without_tax', sa.Numeric(precision=10, scale=2), nullable=True, comment='単価（軽油税抜）'),
    sa.Column('amount_with_tax', sa.Numeric(precision=10, scale=0), nullable=True, comment='金額（軽油税込）'),
    sa.Column('amount_without_tax', sa.Numeric(precision=10, scale=0), nullable=True, comment='金額（軽油税抜）'),
    sa.Column('consumption_tax', sa.Numeric(precision=10, scale=0), nullable=True, comment='消費税'),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=0), nullable=True, comment='合計金額'),
    sa.Column('diesel_tax', sa.Numeric(precision=10, scale=0), nullable=True, comment='軽油税'),
    sa.Column('card_code', sa.String(length=50), nullable=True, comment='カードコード'),
    sa.Column('sales_format', sa.String(length=10), nullable=True, comment='販売形態'),
    sa.Column('processing_category', sa.String(length=10), nullable=True, comment='処理区分'),
    sa.Column('import_date', sa.DateTime(), nullable=True, comment='インポート日時'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日時'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eneos_wing_records', schema=None) as batch_op:
        batch_op.create_index('idx_eneos_wing_date_vehicle', ['fuel_date', 'vehicle_number'], unique=False)
        batch_op.create_index('idx_eneos_wing_station_date', ['station_code', 'fuel_date'], unique=False)

#    with op.batch_alter_table('courses', schema=None) as batch_op:
 #       batch_op.alter_column('fld_コースID',
  #             existing_type=sa.SMALLINT(),
   #            server_default=None,
    #           existing_nullable=False,
     #          autoincrement=True)

#    with op.batch_alter_table('vehicles', schema=None) as batch_op:
 #       batch_op.alter_column('初年度登録年月',
  #             existing_type=sa.TEXT(),
   #            type_=sa.String(),
    #           existing_nullable=True)
     #   batch_op.drop_column('呼称')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('呼称', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='車両呼称（ナンバー下4桁）'))
        batch_op.alter_column('初年度登録年月',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('fld_コースID',
               existing_type=sa.SMALLINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('eneos_wing_records', schema=None) as batch_op:
        batch_op.drop_index('idx_eneos_wing_station_date')
        batch_op.drop_index('idx_eneos_wing_date_vehicle')

    op.drop_table('eneos_wing_records')
    # ### end Alembic commands ###
