"""Employee

Revision ID: 3c79db6d4824
Revises: 05d00ba050bb
Create Date: 2025-05-21 11:24:47.388433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c79db6d4824'
down_revision = '05d00ba050bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False, comment='従業員コード'),
    sa.Column('last_name', sa.String(length=50), nullable=False, comment='姓'),
    sa.Column('first_name', sa.String(length=50), nullable=False, comment='名'),
    sa.Column('last_name_kana', sa.String(length=50), nullable=True, comment='姓（カナ）'),
    sa.Column('first_name_kana', sa.String(length=50), nullable=True, comment='名（カナ）'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='生年月日'),
    sa.Column('join_date', sa.Date(), nullable=True, comment='入社日'),
    sa.Column('department', sa.String(length=50), nullable=True, comment='部署'),
    sa.Column('position', sa.String(length=50), nullable=True, comment='役職'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='メールアドレス'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='電話番号'),
    sa.Column('license_type', sa.String(length=50), nullable=True, comment='免許種別'),
    sa.Column('license_number', sa.String(length=50), nullable=True, comment='免許番号'),
    sa.Column('license_expiry_date', sa.Date(), nullable=True, comment='免許有効期限'),
    sa.Column('is_driver', sa.Boolean(), nullable=True, comment='運転手フラグ'),
    sa.Column('is_mechanic', sa.Boolean(), nullable=True, comment='整備士フラグ'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='在籍フラグ'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備考'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日時'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code')
    )
    #with op.batch_alter_table('courses', schema=None) as batch_op:
     #   batch_op.alter_column('fld_コースID',
      #         existing_type=sa.SMALLINT(),
       #        server_default=None,
        #       existing_nullable=False,
         #      autoincrement=True)

    with op.batch_alter_table('maintenance_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technician_id', sa.Integer(), nullable=True, comment='担当者ID'))
        batch_op.create_foreign_key(None, 'employees', ['technician_id'], ['id'])

    #with op.batch_alter_table('vehicles', schema=None) as batch_op:
    #    batch_op.alter_column('初年度登録年月',
     #          existing_type=sa.TEXT(),
     #          type_=sa.String(),
      #         existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('初年度登録年月',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('maintenance_schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('technician_id')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('fld_コースID',
               existing_type=sa.SMALLINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    op.drop_table('employees')
    # ### end Alembic commands ###
