"""vehicle

Revision ID: 4d50879d53fa
Revises: bdf6040a806c
Create Date: 2025-05-17 16:30:05.338495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d50879d53fa'
down_revision = 'bdf6040a806c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles_bak')
    #with op.batch_alter_table('courses', schema=None) as batch_op:
     #   batch_op.alter_column('fld_コースID',
      #         existing_type=sa.SMALLINT(),
       #        server_default=None,
        #       existing_nullable=False,
         #      autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('fld_コースID',
               existing_type=sa.SMALLINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    op.create_table('vehicles_bak',
    sa.Column('CertInfoImportFileVersion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Acceptoutputno', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('FormType', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ElectCertMgNo', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('CarId', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ElectCertPublishdateE', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ElectCertPublishdateY', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ElectCertPublishdateM', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ElectCertPublishdateD', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('GrantdateE', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('GrantdateY', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('GrantdateM', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('GrantdateD', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TranspotationBureauchiefName', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('EntryNoCarNo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ReggrantdateE', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ReggrantdateY', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ReggrantdateM', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ReggrantdateD', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('FirstregistdateE', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('FirstregistdateY', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('FirstregistdateM', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CarName', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('CarNameCode', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('CarNo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Model', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('EngineModel', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('OwnernameLowLevelChar', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('OwnernameHighLevelChar', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('OwnerAddressChar', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('OwnerAddressNumValue', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('OwnerAddressCode', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('UsernameLowLevelChar', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('UsernameHighLevelChar', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('UserAddressChar', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('UserAddressNumValue', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('UserAddressCode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('UseheadqrterChar', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('UseheadqrterNumValue', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('UseheadqrterCode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('CarKind', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Use', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('PrivateBusiness', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('CarShape', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('CarShapeCode', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('NoteCap', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Cap', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoteMaxloadage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Maxloadage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoteCarWgt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('CarWgt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoteCarTotalWgt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('CarTotalWgt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoteLength', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoteWidth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoteHeight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('FfAxWgt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('FrAxWgt', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('RfAxWgt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('RrAxWgt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Displacement', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('FuelClass', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ModelSpecifyNo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ClassifyAroundNo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ValidPeriodExpirdateE', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ValidPeriodExpirdateY', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ValidPeriodExpirdateM', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ValidPeriodExpirdateD', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoteInfo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoEntryNoCarNo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoCarNo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoValidPeriodExpirdate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoModel', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoModelSpecifyNoClassifyAroundNo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoCharInfo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoEngineModel', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoCarNoStampPlace', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoFirstregistdate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoFfAxWgt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoFrAxWgt', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoRfAxWgt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoRrAxWgt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoNoiseReg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoNearNoiseReg', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoDriveMethod', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoOpacimeterMeasCar', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoNoxPmMeasMode', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoNoxValue', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoPmValue', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoSafeStdDate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TwodimensionCodeInfoFuelClassCode', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('RegistCarLightCar', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('CarId', name='vehicles_pkey')
    )
    # ### end Alembic commands ###
