"""add kitaseki

Revision ID: 540ec46b7a8f
Revises: 11b672caa2a3
Create Date: 2025-06-11 10:03:47.216923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540ec46b7a8f'
down_revision = '11b672caa2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitaseki_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_code', sa.String(length=20), nullable=True, comment='取引先コード'),
    sa.Column('user_code', sa.String(length=20), nullable=True, comment='取引先ユーザーコード'),
    sa.Column('customer_type', sa.String(length=10), nullable=True, comment='取引先親子区分'),
    sa.Column('transaction_date', sa.Date(), nullable=False, comment='取引年月日'),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False, comment='車番'),
    sa.Column('fuel_station_type', sa.String(length=10), nullable=True, comment='給油所区分'),
    sa.Column('highway_type', sa.String(length=10), nullable=True, comment='高速区分'),
    sa.Column('fuel_company_code', sa.String(length=20), nullable=True, comment='給油先会社コード'),
    sa.Column('fuel_station_code', sa.String(length=20), nullable=True, comment='給油先SSコード'),
    sa.Column('fuel_station_name', sa.String(length=100), nullable=True, comment='給油所名'),
    sa.Column('product_code', sa.String(length=20), nullable=True, comment='商品コード'),
    sa.Column('product_name', sa.String(length=100), nullable=True, comment='商品名'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False, comment='数量（リットル）'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='単価'),
    sa.Column('product_amount', sa.Integer(), nullable=True, comment='商品代'),
    sa.Column('consumption_tax', sa.Integer(), nullable=True, comment='参考消費税'),
    sa.Column('diesel_tax', sa.Integer(), nullable=True, comment='軽油税'),
    sa.Column('voucher_number', sa.String(length=20), nullable=True, comment='伝票番号'),
    sa.Column('line_number', sa.Integer(), nullable=True, comment='行番号'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日時'),
    sa.Column('import_batch_id', sa.String(length=50), nullable=True, comment='インポートバッチID'),
    sa.PrimaryKeyConstraint('id')
    )
  #  with op.batch_alter_table('courses', schema=None) as batch_op:
   #     batch_op.alter_column('fld_コースID',
    #           existing_type=sa.SMALLINT(),
     #          server_default=None,
      #         existing_nullable=False,
       #        autoincrement=True)

#    with op.batch_alter_table('vehicles', schema=None) as batch_op:
 #       batch_op.alter_column('初年度登録年月',
  #             existing_type=sa.TEXT(),
   #            type_=sa.String(),
    #           existing_nullable=True)
     #   batch_op.drop_column('呼称')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('呼称', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='車両呼称（ナンバー下4桁）'))
        batch_op.alter_column('初年度登録年月',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('fld_コースID',
               existing_type=sa.SMALLINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    op.drop_table('kitaseki_records')
    # ### end Alembic commands ###
