"""xxxx

Revision ID: 6ef86079c6cd
Revises: 
Create Date: 2025-05-02 06:09:12.125281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ef86079c6cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('fld_取引先ID', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('fld_会社名', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('fld_取引先ID')
    )
    op.create_table('course_groups',
    sa.Column('fld_グループID', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('fld_コースID', mysql.SMALLINT(display_width=6), nullable=True),
    sa.Column('fld_コースグループID', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('fld_得意先コード', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('fld_得意先名', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('fld_グループID')
    )
    op.create_table('crate_weights',
    sa.Column('fld_クレート種別', sa.String(length=255), nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('fld_重量', mysql.SMALLINT(display_width=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etc_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('departure_ic', sa.String(length=100), nullable=True),
    sa.Column('arrival_ic', sa.String(length=100), nullable=True),
    sa.Column('original_fee', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('final_fee', sa.Integer(), nullable=True),
    sa.Column('vehicle_number', sa.String(length=64), nullable=True),
    sa.Column('etc_card_number', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loading_data',
    sa.Column('fld_積込量ID', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('fld_仕分日', sa.DateTime(), nullable=True),
    sa.Column('fld_コースID', mysql.SMALLINT(display_width=6), nullable=True),
    sa.Column('fld_コース内グループ', sa.String(length=255), nullable=True),
    sa.Column('fld_赤クレート数', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('fld_平クレート数', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('fld_青クレート数', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('fld_段ボール数', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('fld_学乳数', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('fld_データ入力日', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('fld_積込量ID')
    )
    op.create_table('loading_methods',
    sa.Column('fld_積み方ID', sa.String(length=255), nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('fld_赤PL', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('fld_平PL', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('fld_青PL', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('fld_段PL', mysql.INTEGER(display_width=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicles',
    sa.Column('CertInfoImportFileVersion', sa.Float(), nullable=True),
    sa.Column('Acceptoutputno', sa.Integer(), nullable=True),
    sa.Column('FormType', sa.String(length=255), nullable=True),
    sa.Column('ElectCertMgNo', sa.Integer(), nullable=True),
    sa.Column('CarId', sa.String(length=255), nullable=False),
    sa.Column('ElectCertPublishdateE', sa.String(length=255), nullable=True),
    sa.Column('ElectCertPublishdateY', sa.Integer(), nullable=True),
    sa.Column('ElectCertPublishdateM', sa.Integer(), nullable=True),
    sa.Column('ElectCertPublishdateD', sa.Integer(), nullable=True),
    sa.Column('GrantdateE', sa.String(length=255), nullable=True),
    sa.Column('GrantdateY', sa.Integer(), nullable=True),
    sa.Column('GrantdateM', sa.Integer(), nullable=True),
    sa.Column('GrantdateD', sa.Integer(), nullable=True),
    sa.Column('TranspotationBureauchiefName', sa.String(length=255), nullable=True),
    sa.Column('EntryNoCarNo', sa.String(length=255), nullable=True),
    sa.Column('ReggrantdateE', sa.String(length=255), nullable=True),
    sa.Column('ReggrantdateY', sa.Integer(), nullable=True),
    sa.Column('ReggrantdateM', sa.Integer(), nullable=True),
    sa.Column('ReggrantdateD', sa.Integer(), nullable=True),
    sa.Column('FirstregistdateE', sa.String(length=255), nullable=True),
    sa.Column('FirstregistdateY', sa.Integer(), nullable=True),
    sa.Column('FirstregistdateM', sa.Integer(), nullable=True),
    sa.Column('CarName', sa.String(length=255), nullable=True),
    sa.Column('CarNameCode', sa.String(length=255), nullable=True),
    sa.Column('CarNo', sa.String(length=255), nullable=True),
    sa.Column('Model', sa.String(length=255), nullable=True),
    sa.Column('EngineModel', sa.String(length=255), nullable=True),
    sa.Column('OwnernameLowLevelChar', sa.String(length=255), nullable=True),
    sa.Column('OwnernameHighLevelChar', sa.String(length=255), nullable=True),
    sa.Column('OwnerAddressChar', sa.String(length=255), nullable=True),
    sa.Column('OwnerAddressNumValue', sa.String(length=255), nullable=True),
    sa.Column('OwnerAddressCode', sa.String(length=255), nullable=True),
    sa.Column('UsernameLowLevelChar', sa.String(length=255), nullable=True),
    sa.Column('UsernameHighLevelChar', sa.String(length=255), nullable=True),
    sa.Column('UserAddressChar', sa.String(length=255), nullable=True),
    sa.Column('UserAddressNumValue', sa.Float(), nullable=True),
    sa.Column('UserAddressCode', sa.Float(), nullable=True),
    sa.Column('UseheadqrterChar', sa.String(length=255), nullable=True),
    sa.Column('UseheadqrterNumValue', sa.Float(), nullable=True),
    sa.Column('UseheadqrterCode', sa.Float(), nullable=True),
    sa.Column('CarKind', sa.String(length=255), nullable=True),
    sa.Column('Use', sa.String(length=255), nullable=True),
    sa.Column('PrivateBusiness', sa.String(length=255), nullable=True),
    sa.Column('CarShape', sa.String(length=255), nullable=True),
    sa.Column('CarShapeCode', sa.String(length=255), nullable=True),
    sa.Column('NoteCap', sa.Float(), nullable=True),
    sa.Column('Cap', sa.Integer(), nullable=True),
    sa.Column('NoteMaxloadage', sa.Float(), nullable=True),
    sa.Column('Maxloadage', sa.Integer(), nullable=True),
    sa.Column('NoteCarWgt', sa.Float(), nullable=True),
    sa.Column('CarWgt', sa.Integer(), nullable=True),
    sa.Column('NoteCarTotalWgt', sa.Float(), nullable=True),
    sa.Column('CarTotalWgt', sa.Integer(), nullable=True),
    sa.Column('NoteLength', sa.Float(), nullable=True),
    sa.Column('Length', sa.Integer(), nullable=True),
    sa.Column('NoteWidth', sa.Float(), nullable=True),
    sa.Column('Width', sa.Integer(), nullable=True),
    sa.Column('NoteHeight', sa.Float(), nullable=True),
    sa.Column('Height', sa.Integer(), nullable=True),
    sa.Column('FfAxWgt', sa.Integer(), nullable=True),
    sa.Column('FrAxWgt', sa.String(length=255), nullable=True),
    sa.Column('RfAxWgt', sa.Integer(), nullable=True),
    sa.Column('RrAxWgt', sa.Integer(), nullable=True),
    sa.Column('Displacement', sa.Float(), nullable=True),
    sa.Column('FuelClass', sa.String(length=255), nullable=True),
    sa.Column('ModelSpecifyNo', sa.Float(), nullable=True),
    sa.Column('ClassifyAroundNo', sa.Float(), nullable=True),
    sa.Column('ValidPeriodExpirdateE', sa.String(length=255), nullable=True),
    sa.Column('ValidPeriodExpirdateY', sa.Integer(), nullable=True),
    sa.Column('ValidPeriodExpirdateM', sa.Integer(), nullable=True),
    sa.Column('ValidPeriodExpirdateD', sa.Integer(), nullable=True),
    sa.Column('NoteInfo', sa.String(length=255), nullable=True),
    sa.Column('TwodimensionCodeInfoEntryNoCarNo', sa.String(length=255), nullable=True),
    sa.Column('TwodimensionCodeInfoCarNo', sa.String(length=255), nullable=True),
    sa.Column('TwodimensionCodeInfoValidPeriodExpirdate', sa.Integer(), nullable=True),
    sa.Column('TwodimensionCodeInfoModel', sa.String(length=255), nullable=True),
    sa.Column('TwodimensionCodeInfoModelSpecifyNoClassifyAroundNo', sa.Float(), nullable=True),
    sa.Column('TwodimensionCodeInfoCharInfo', sa.String(length=255), nullable=True),
    sa.Column('TwodimensionCodeInfoEngineModel', sa.String(length=255), nullable=True),
    sa.Column('TwodimensionCodeInfoCarNoStampPlace', sa.String(length=255), nullable=True),
    sa.Column('TwodimensionCodeInfoFirstregistdate', sa.Integer(), nullable=True),
    sa.Column('TwodimensionCodeInfoFfAxWgt', sa.Integer(), nullable=True),
    sa.Column('TwodimensionCodeInfoFrAxWgt', sa.String(length=255), nullable=True),
    sa.Column('TwodimensionCodeInfoRfAxWgt', sa.Integer(), nullable=True),
    sa.Column('TwodimensionCodeInfoRrAxWgt', sa.Integer(), nullable=True),
    sa.Column('TwodimensionCodeInfoNoiseReg', sa.Integer(), nullable=True),
    sa.Column('TwodimensionCodeInfoNearNoiseReg', sa.String(length=255), nullable=True),
    sa.Column('TwodimensionCodeInfoDriveMethod', sa.String(length=255), nullable=True),
    sa.Column('TwodimensionCodeInfoOpacimeterMeasCar', sa.Integer(), nullable=True),
    sa.Column('TwodimensionCodeInfoNoxPmMeasMode', sa.String(length=255), nullable=True),
    sa.Column('TwodimensionCodeInfoNoxValue', sa.String(length=255), nullable=True),
    sa.Column('TwodimensionCodeInfoPmValue', sa.String(length=255), nullable=True),
    sa.Column('TwodimensionCodeInfoSafeStdDate', sa.Integer(), nullable=True),
    sa.Column('TwodimensionCodeInfoFuelClassCode', sa.Integer(), nullable=True),
    sa.Column('RegistCarLightCar', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('CarId')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('fld_コースID',
               existing_type=sa.SMALLINT(),
               existing_nullable=False)
        batch_op.alter_column('fld_仕分日係数',
               existing_type=sa.SMALLINT(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.alter_column('fld_仕分日係数',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.SMALLINT(),
               existing_nullable=True)
        batch_op.alter_column('fld_コースID',
               existing_type=sa.SMALLINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('loading_methods')
    op.drop_table('loading_data')
    op.drop_table('etc_usage')
    op.drop_table('crate_weights')
    op.drop_table('course_groups')
    op.drop_table('clients')
    # ### end Alembic commands ###
