"""Add fuel service management tables

Revision ID: b3f16d9ee227
Revises: bbedfcf7f371
Create Date: 2025-06-10 09:48:55.568793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f16d9ee227'
down_revision = 'bbedfcf7f371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  #  with op.batch_alter_table('courses', schema=None) as batch_op:
   #     batch_op.alter_column('fld_コースID',
    #           existing_type=sa.SMALLINT(),
          #     server_default=None,
     #          existing_nullable=False,
      #         autoincrement=True)

    ##   batch_op.alter_column('初年度登録年月',
               existing_type=sa.TEXT(),
      #         type_=sa.String(),
       #        existing_nullable=True)
       # batch_op.drop_column('呼称')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('呼称', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='車両呼称（ナンバー下4桁）'))
        batch_op.alter_column('初年度登録年月',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('fld_コースID',
               existing_type=sa.SMALLINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
