"""change fld_重量

Revision ID: bdf6040a806c
Revises: 6ef86079c6cd
Create Date: 2025-05-02 11:15:03.610933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdf6040a806c'
down_revision = '6ef86079c6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('fld_コースID',
               existing_type=sa.SMALLINT(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('crate_weights', schema=None) as batch_op:
        batch_op.alter_column('fld_重量',
               existing_type=sa.SMALLINT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crate_weights', schema=None) as batch_op:
        batch_op.alter_column('fld_重量',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.SMALLINT(),
               existing_nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('fld_コースID',
               existing_type=sa.SMALLINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
