"""retouch kitaseki

Revision ID: d4de62e180d8
Revises: 540ec46b7a8f
Create Date: 2025-06-11 10:18:37.619738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4de62e180d8'
down_revision = '540ec46b7a8f'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
 #   with op.batch_alter_table('courses', schema=None) as batch_op:
  #      batch_op.alter_column('fld_コースID',
   #            existing_type=sa.SMALLINT(),
    #           server_default=None,
     #          existing_nullable=False,
      #         autoincrement=True)

#    with op.batch_alter_table('vehicles', schema=None) as batch_op:
 #       batch_op.alter_column('初年度登録年月',
  #             existing_type=sa.TEXT(),
   #            type_=sa.String(),
    #           existing_nullable=True)
     #   batch_op.drop_column('呼称')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('呼称', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='車両呼称（ナンバー下4桁）'))
        batch_op.alter_column('初年度登録年月',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('fld_コースID',
               existing_type=sa.SMALLINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
